### ISSUE TITLE
Build - Cannot find macro 

### ISSUE THREAD

**Issue by mmacedoeu** [rabite0/hunter#70]
Building from source after clone generates error:
```
error: cannot find macro `format_err!` in this scope
   --> src/hunter-media.rs:723:31
    |
723 |             let sixfail = |e| format_err!("Sixel failed with: {:?}", e);
    |                               ^^^^^^^^^^ help: a macro with a similar name exists: `format_args`
```

```
rustc --version
rustc 1.39.0-nightly (f7af19c27 2019-08-15)
```

**Comment by rabite0** [comment]
Should be fixed. Sorry it took so long :)

**Comment by mmacedoeu** [comment]
Error still present:

```
error: cannot find macro `format_err` in this scope
   --> src/hunter-media.rs:722:31
    |
722 |               let sixfail = |e| format_err!("Sixel failed with: {:?}", e);
    |                                 ^^^^^^^^^^ help: a macro with a similar name exists: `format_args`

error: aborting due to previous error
```
rustc --version
rustc 1.42.0-nightly (b5a3341f1 2020-01-20)

Build with:

cargo install --no-default-features --features="img sixel" --path .

**Comment by rabite0** [comment]
Oops, sorry, I should have paid more attention.
Should be fixed now.

**Comment by rabite0** [comment]
If it still doesn't work feel free to reopen.
