### ISSUE TITLE
Unwanted jumps

### ISSUE THREAD

**Issue by magnetophon** [rabite0/hunter#75]
When I hold down PgDn in a huge dir, hunter scrolls down at incredible speed, but at the end it jumps to my home dir.

**Comment by rabite0** [comment]
Can't really replicate this.
How huge? Have you done any customization to the key bindings? Is there a message in the log? Should be mapped to "g".

**Comment by magnetophon** [comment]
I found out it happens in alacritty, but not in urxvt.
Is it a bug in alacritty?

**Comment by rabite0** [comment]
Interesting. Doesn't happen on my machine, even with alacritty. It could be that it reports the wrong size, or that hunter screws up the calculation of the current position.

Can you run this to find out the number of columns/rows:

`tput cols`
`tput lines`

And then go into a large directory and go to the first file at the top (press "<"). Then select the last file you see without scrolling. At the bottom left is a counter which shows the current position and the total number of files. The current position should be the number of lines from `tput lines` minus 2 (top/bottom bar). If this doesn't add up there's something screwed up.

**Comment by magnetophon** [comment]
I get:

```
❯ tput cols
266
❯ tput lines
73
```
Current possition: 71
So that's OK.

**Comment by rabite0** [comment]
Thank you, that  rules out some crazy stuff happening. I'll take a look at the parts of the code which could trigger this behavior.

**Comment by magnetophon** [comment]
While testing this in the latest version, (wow, its FAST!!!), I got a crash:
```
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/listview.rs:401:9
stack backtrace:
^[[6~^[[6~^[[6~^[[6~^[[6~^[[6~^[[6~^[[6~   0:     0x56076ac1accc - backtrace::backtrace::libunwind::trace::h591288bd927a03ee
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/libunwind.rs:88
   1:     0x56076ac1accc - backtrace::backtrace::trace_unsynchronized::h9ab029e33406f52d
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/mod.rs:66
   2:     0x56076ac1accc - std::sys_common::backtrace::_print_fmt::hb2daadb8b8fbf429
                               at src/libstd/sys_common/backtrace.rs:77
   3:     0x56076ac1accc - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h0c653e1531b89531
                               at src/libstd/sys_common/backtrace.rs:59
^[[6~   4:     0x56076ab5cf4c - core::fmt::write::hb31f400b50d155bc
                               at src/libcore/fmt/mod.rs:1052
   ^[[6~5:     0x56076ac1a566 - std::io::Write::write_fmt::h669133ec594d8b98
                               at src/libstd/io/mod.rs:1426
   6:     0x56076ac1a195 - std::sys_common::backtrace::_print::h63852c0b043a355f
                               at src/libstd/sys_common/backtrace.rs:62
   7:     0x56076ac1a195 - std::sys_common::backtrace::print::h644df75b68466824
                               at src/libstd/sys_common/backtrace.rs:49
   8:     0x56076ac1a195 - std::panicking::default_hook::{{closure}}::h01d735e76ba96353
                               at src/libstd/panicking.rs:204
   9:     0x56076ac19a4a - std::panicking::default_hook::hf4c2df09a3867af3
                               at src/libstd/panicking.rs:224
  10:     0x56076aaecda9 - hunter::die_gracefully::{{closure}}::h0ebaf35de2cff8c8
  11:     0x56076ac19636 - std::panicking::rust_panic_with_hook::h28a983eb699ac39a
                               at src/libstd/panicking.rs:476
  12:     0x56076ac19418 - rust_begin_unwind
                               at src/libstd/panicking.rs:380
  13:     0x56076ab5b430 - core::panicking::panic_fmt::h3f7fc5990a866d0e
                               at src/libcore/panicking.rs:85
  14:     0x56076ab5b24c - core::panicking::panic::h6f0394026b0eb664
                               at src/libcore/panicking.rs:52
  15:     0x56076aa9a034 - hunter::widget::Widget::handle_input::h1b89448353e31fa7
  16:     0x56076aaf092c - hunter::main::h4712cae76172520e
  17:     0x56076a9be3e5 - std::rt::lang_start::{{closure}}::hb6e903267e9e9462
  18:     0x56076aaf442f - main
  19:     0x7f7df4579b8e - __libc_start_main
  20:     0x56076a9991aa - _start
  21:                0x0 - <unknown>
^[[6~%                                               
```

**Comment by rabite0** [comment]
Yeah, I noticed it too. Currently working on this.
All the optimizing caused some unfortunate side-effects like this. I added a warning to the readme that the current master branch is a big wonky. I will fix this shortly.

**Comment by rabite0** [comment]
Crash appears to be fixed with commit 0f7be9e.

**Comment by magnetophon** [comment]
Yup, crash is fixed.  :)

Jumps are still there.

**Comment by rabite0** [comment]
Yeah, I didn't forget about this. Btw, does this happen with the tagged 1.3.5 release. or too, or is this a new bug from the optimizations?
Can you post your alacritty config, maybe there's some hint in there. And which version/commit are you running?

**Comment by magnetophon** [comment]
It also happens in v1.3.5.

Here's [my config](https://github.com/magnetophon/.dot/blob/master/common/.config/alacritty/alacritty.yml).
I'm running alacritty 0.4.1.

**Comment by rabite0** [comment]
Great, will look into this today!

**Comment by rabite0** [comment]
Sorry for not getting back to you earlier. I'm still kinda stuck in that optimization rabbit hole and just couldn't stop. (It was worth it though, hunter is faster than nnn now)
Anyway, I pushed anew branch (`jumpdebug`) that you can try to diagnose the issue. It will print out the key you press as well as whatever action it finds in the list of key bindings. Redirect with `2>dbg.txt` or whatever and post the results.
I  suspect it could be due to a key being mapped multiple times (either in hunter or in alacritty itself) or something like that. Would be great if it was as simple as that.

**Comment by magnetophon** [comment]
Yes, the speed of the latest master is incredible!  Well done!
lol at "fastest file manager in the galaxy"!

Here's the debug txt:
```
[src/keybind.rs:64] movement = PageDown
[src/keybind.rs:64] movement = PageDown
[src/keybind.rs:64] movement = PageDown
[src/keybind.rs:64] movement = PageDown
[src/keybind.rs:64] movement = PageDown
[src/keybind.rs:64] movement = PageDown
[src/keybind.rs:64] movement = PageDown
[src/keybind.rs:64] movement = PageDown
[src/keybind.rs:64] movement = PageDown
[src/keybind.rs:64] movement = PageDown
[src/keybind.rs:64] movement = PageDown
[src/keybind.rs:64] movement = PageDown
[src/keybind.rs:64] movement = PageDown
[src/keybind.rs:64] movement = PageDown
[src/keybind.rs:64] movement = PageDown
[src/keybind.rs:64] movement = PageDown
[src/keybind.rs:64] movement = PageDown
[src/keybind.rs:64] movement = PageDown
[src/keybind.rs:77] action = GotoHome
[src/keybind.rs:64] movement = PageDown
[src/keybind.rs:64] movement = PageDown
[src/keybind.rs:77] action = GotoHome
[src/keybind.rs:64] movement = PageDown
[src/keybind.rs:64] movement = PageDown
[src/keybind.rs:77] action = GotoHome
[src/keybind.rs:64] movement = PageDown
[src/keybind.rs:64] movement = PageDown
[src/keybind.rs:64] movement = PageDown
[src/keybind.rs:64] movement = PageDown
[src/keybind.rs:77] action = GotoHome
[src/keybind.rs:64] movement = PageDown
[src/keybind.rs:64] movement = PageDown
[src/keybind.rs:64] movement = PageDown
[src/keybind.rs:64] movement = PageDown
[src/keybind.rs:64] movement = PageDown
[src/keybind.rs:64] movement = PageDown
[src/keybind.rs:64] movement = PageDown
[src/keybind.rs:64] movement = PageDown
[src/keybind.rs:64] movement = PageDown
[src/keybind.rs:64] movement = PageDown
[src/keybind.rs:64] movement = PageDown
[src/keybind.rs:64] movement = PageDown
[src/keybind.rs:64] movement = PageDown
[src/keybind.rs:64] movement = PageDown
[src/keybind.rs:64] movement = PageDown
[src/keybind.rs:64] movement = PageDown
[src/keybind.rs:64] movement = PageDown
[src/keybind.rs:64] movement = PageDown
[src/keybind.rs:64] movement = PageDown
[src/keybind.rs:64] movement = PageDown
[src/keybind.rs:64] movement = PageDown
[src/keybind.rs:64] movement = PageDown
```

**Comment by rabite0** [comment]
Huh, that's weird You can probably tell that "GotoHome" shouldn't be there. I pushed a new version that contains a possible "fix" and prints some more diagnostics. If you have a ~/.config/hunter/keys file you need to change the binding for GotoHome in there from "~" so something else (I just picked "9"). If that works, please add back the "~" binding and post the output from THAT.

It seems like alacritty either sends a superfluous "~" character, or hunter somehow interprets the PageDown key wrong and it turns into that. If that's not it,  as a sanity check, can you test if it also happens with when you use M/Alt-v instead of the actual PageDown key?

**Comment by magnetophon** [comment]
I pulled on master and rebuilt, but the issue is still there.
I don't have a ``~/.config/hunter/keys`` file.
``Alt-v`` does nothing as far as I can tell.

**Comment by rabite0** [comment]
Still, can you post the output? It contains some more information that I need to  find out what's happening.

**Comment by magnetophon** [comment]
Sorry, I don't understand what exactly you want me to post.

**Comment by rabite0** [comment]
The output from the new debug build. It prints some more information than the previous one and that would be useful to see.

I tested with some other terminals earlier and at least xterm had issues with some keys. I'm starting to think that alacritty is the culprit after all and sends the wrong key code, but I can't say for sure without more information.

**Comment by magnetophon** [comment]
Here you go: https://termbin.com/2ba2.
It stopped jumping now though.

**Comment by rabite0** [comment]
Ok seems like either alacritty sends a `~` when it shouldn't, or termion is doing something wonky. It's hard to say which one causes the problem. I noticed something in your alacritty config. The line
`
# Send ESC (\x1b) before characters when alt is pressed.
alt_send_esc: true
`
might be the culprit. You could try without this setting.

Also this line:
`
  - { key: PageDown,                chars: "\x1b[6~"                     }
`
There is a `~` there. Might this be the cause of the jumps?

Anyway, if all that doesn't help, you can just create a `keys` file in `~/.config/hunter/` and set PageDown to something else. By default there's also a M-v binding for it for example. If hunter finds a `keys` file it doesn't load the built-in defaults, but just what it finds in the `keys` file. At least that should happen.

In config.tar.gz you can find a `keys` config file with the default settings and go from there. If you didn't do any customization you can just delete ~./.config/hunter` and the next time hunter starts it should extract the whole config.tar.gz on its own and you should find it in the config directory. 

I'm not sure there is something else I can do about this. If the terminal sends a `~` hunter just does what the key is bound to, which by default is to go into `~/`. However when it finds a `keys` config it will not use any default bindings which should fix your problem

**Comment by magnetophon** [comment]
I tried changing those alacritty settings but that didn't solve it.
When I lower the  key repeat rate, the issue goes away though!
IOW:
``xset r rate 180 100`` -> jumps
``xset r rate 180 10`` -> no jumps
Can you reproduce it that way?  Or maybe even higher rates are needed on your PC?

**Comment by rabite0** [comment]
YES! That does it! (at 200 keys/s)
Weird, but now I can replicate it! Good idea.

I have a feeling that it might be related to the input flushing, now that I think about it. I wanted to take that out for a long time, because it also breaks pasting things into the minibuffer not work.

**Comment by magnetophon** [comment]
Great!

Re: graphics: what are your feelings on uberzug? I'm quite happy with how it works in combination with alacritty and ranger.

**Comment by rabite0** [comment]
Indeed, it was because of input buffer flushing. Seems like input isn't "atomic" and thus partial input gets garbled. This appears to be fixed on master for any repeat rate.   This way pasting into the minibuffer works as intended again, and the youtube-dl custom action example makes sense again, now...

I've been thinking about adding support for more graphics backends for quite some time. I started work on a new plain unicode halfblock mode with 256 colors as opposed to true color and the urxvt protocol. Honestly, "protocol" is too fancy of a word. Except for SIXEL/kitty all the "protocols" I'm aware of are just a simple escape code with a path to some image file sandwiched somewhere in between. As such adding support for urxvt, iterm2 and I dunno what else is basically just adding the option and the correct escape code. w3mimage or überzug seems like a good fallback if nothing else would work, so that's nice to have. Not sure how well it works for gif/video (kitty is REALLY good at this ;)), but it's coming one way or another.

**Comment by magnetophon** [comment]
Nailed it!
